### ISSUE TITLE
Is it possible to integrate the provider with kubelogin exec authentication?

### ISSUE THREAD

**Issue by audunsolemdal** [fluxcd/terraform-provider-flux#489] opened 2023-05-31 14:11 UTC
Is it currently possible to integrate workload identity / managed identity based kubelogin into the flux provider as of now? E.g. for the kubectl and helm providers I can authenticate in this manner

```hcl
provider "kubectl" {
  host                   = data.azurerm_kubernetes_cluster.current.kube_config[0].host
  apply_retry_count      = 5
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.current.kube_config[0].cluster_ca_certificate)

  # Using kubelogin to get an AAD token for the cluster. Pre-req that kubelogin is installed on jumpbox.
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "kubelogin"
    args = [
      "get-token",
      "--login",
      "workloadidentity",
      "--server-id",
      data.azuread_service_principal.aks_aad_server.application_id,
      "--client-id",
      data.azuread_client_config.current.client_id,
      "--tenant-id",
      data.azurerm_subscription.current.tenant_id,
      "--authority-host",
      "https://login.microsoftonline.com/",
      "--federated-token-file",
      "/home/azbuildadmin/.token"
    ]
  }
}
```

where  the content in `/home/azbuildadmin/.token` is an Azure AD JWT retrieved via Github Actions via identity federation

I tried config such as the following, but I assume the token needs to be the exchanged token rather than the AAD JWT, as I get permissions hinting towards permission denied ` Error: Could not get NetworkPolicy flux-system/allow-webhooks failed to get API group resources:`

```hcl
provider "flux" {
  git = {
    url = "https://github.com/myorg/myrepo"
  }
  kubernetes = {
    token = "/home/azbuildadmin/.token"
    cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.current.kube_config[0].cluster_ca_certificate)
  }
}
```

**Comment by stefanprodan** [comment] 2023-05-31 14:13
Duplicate of: https://github.com/fluxcd/terraform-provider-flux/issues/406

**Closed** 2023-05-31 14:16 UTC
