### ISSUE TITLE
(DOCUMENT) Moving config to provider

### ISSUE THREAD

**Issue by cdenneen** [fluxcd/terraform-provider-flux#395] opened 2023-03-06 14:24 UTC
So the changes to move `git` and `kubernetes` schemas to providers does work and has been tested but creates a known chicken-egg scenario that I just want to make others aware of.

```hcl
provider "flux" {
  kubernetes = {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
    token                  = data.aws_eks_cluster_auth.default.token
  }
  git = {
    url = "ssh://git@gitlab.example.com/${var.gitlab_project_path}/${var.repository_name}.git"
    ssh = {
      username    = "git"
      private_key = tls_private_key.flux.private_key_pem
    }
  }
}

provider "kubectl" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  token                  = data.aws_eks_cluster_auth.default.token
  load_config_file       = false
}

provider "gitlab" {
  base_url = "https://gitlab.example.com/api/v4/"
  token    = var.gitlab_token
}

resource "tls_private_key" "flux" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P256"
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
}

resource "flux_bootstrap_git" "this" {
  path                   = "clusters/${var.cluster_name}"
  branch                 = "main"
  namespace              = "flux-system"
  components_extra       = var.components_extra
  toleration_keys        = ["CriticalAddonsOnly"]
  kustomization_override = file("${path.module}/kustomization-override.yaml")
}

data "gitlab_project" "main" {
  id = "${var.gitlab_project_path}/${var.repository_name}"
}

resource "gitlab_deploy_key" "flux" {
  title    = var.cluster_name
  project  = data.gitlab_project.main.id
  key      = tls_private_key.flux.public_key_openssh
  can_push = true
}

```

So the first thing you will notice bringing this stack up on a clean stack is:

```
╷
│ Error: Unable to get authentication options
│
│   with provider["fluxcd/flux"],
│   on flux.tf line 1, in provider "flux":
│    1: provider "flux" {
│
│ ssh scheme cannot be used without private key
```

you can bypass this by doing an apply on `terraform apply -target tls_private_key.flux`

Once you are past that then doing a normal apply will now error that the `kubernetes` endpoint isn't known.
So now you have to `terraform apply -target module.eks`

Once those are both created you can then run `terraform apply` without any issues.

This is just information to help people understand the dependency issue created by moving these configurations to the provider.

> You can use [expressions](https://developer.hashicorp.com/terraform/language/expressions) in the values of these configuration arguments, but can only reference values that are known before the configuration is applied. This means you can safely reference input variables, but not attributes exported by resources (with an exception for resource arguments that are specified directly in the configuration).
> reference: https://developer.hashicorp.com/terraform/language/providers/configuration

Just wanted to point this out because before moving the configuration to provider it wasn't an issue but now it is.

I could technically solve this by taking the TF plans and breaking them into different "folders" and then apply the `certs` one, apply the `eks` one, and then apply the `flux` one.  It would however require the references to these configurations to be modified and based on `data sources`. (Making them 3 submodules of a larger project won't work because it's still an issue with the config needing to be known during the plan compilation).

**Comment by Sturgelose** [comment] 2023-10-25 12:34
Here we have another similar use-case.

If we want to create multiple kubernetes clusters in the same TF state, this forces to create one specific provider for each combination of repo+kubernetes cluster.

Which... adds some complexity to the code. Using the original datasource, we could create one dynamically for each cluster, but now this is impossible.

Alternatively, we would try to handle the kubernetes side manually with Helm, but this provider AFAIK does not expose a way to "just create the bootstrap resources in the git repo" and as a result it is less easy to configure the setup.

Also, the provider and resources default to create the commits in the GH repo using the provided deploy key. It would be great to have the deploy key read-only and use a GitHub App instead to create the commits (we are doing so for some extra config we add into the flux folder). This makes sure that the cluster cannot edit itself or autoinstall things as the only moment the deploy key should have access to write to the repo should be during installation (AFAIK) .

**Comment by swade1987** [comment] 2024-04-01 13:26
Hi @cdenneen 👋

I hope you are doing well! As part of our ongoing effort to maintain and improve the quality of our project, I've been reviewing open issues and came across the one you've reported. First off, thank you for taking the time to contribute by reporting this issue; your input is crucial to us.

Upon reviewing the details of your issue, I noticed that it involves the use of a resource or feature that has yet to be supported since the 1.0.0 release of our project, which was approximately 9 months ago. This might be a key factor in the challenges you're experiencing. We understand that changes and deprecations can impact your work, and we're here to help navigate these transitions. If there are specific reasons you've continued using this unsupported resource or if there's any way we can assist in migrating to a supported alternative, please let us know.

Additionally, to ensure the efficient management of our issue tracker and to focus on issues that are actively affecting our community, we have implemented a policy for issues that remain inactive. If there is no activity on this issue within the next 3 weeks, we will consider the issue inactive and close it for you. This doesn't mean your issue is not important to us, but rather that we aim to keep our focus on actively pursued concerns. Of course, if the issue continues or if you have further updates in the future, feel free to reopen the issue or create a new one.

Thank you once again for your contribution to our project. Your feedback not only helps us improve but also supports the broader community in overcoming similar challenges. We look forward to hearing from you and hope to resolve any outstanding concerns together.

Best regards,

Steve

**Comment by swade1987** [comment] 2024-04-01 14:20
@cdenneen sorry I got too copy and paste happy. I meant to post a different comment (incoming)

**Comment by swade1987** [comment] 2024-04-01 19:11
Hey @cdenneen 👋  

I wanted to share my thoughts regarding the issue you're experiencing. From my perspective, the root cause might be related more to the structure of Terraform and the sequence of execution rather than an issue specific to the provider. I've been utilizing EKS with GitLab and flux_bootstrap_git for some time now, and I've noticed that our structure differs from what you've described. Perhaps exploring adjustments in the Terraform structure might offer some insights or solutions (see below).

1. We  create all our Gitlab repositories in either one Terraform repository called `tf-gitlab`
2. We create all deploy keys in a Terraform repository called `tf-keypairs`

Then in our main `kubernetes` module we reference the deploy key via remote state (see example below)

```
provider "flux" {
  git = {
    url    = "ssh://${var.flux_bootstrap_configuration["git_repo"]}"
    branch = "main"
    ssh = {
      username    = "git"
      private_key = data.terraform_remote_state.keypairs.outputs.flux_ssh_key["private"]
    }
  }
  kubernetes = {
    host                   = module.cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(module.cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
}
``` 

Looking forward to your thoughts on this.

**Comment by swade1987** [comment] 2024-04-09 10:53
I am going to close this as it is really a discussion @cdenneen, which should be moved across to https://github.com/fluxcd/flux2/discussions

**Closed by swade1987** 2024-04-09 10:53 UTC
Labels: request for feedback
