### ISSUE TITLE
problem with sample config

### ISSUE THREAD

**Issue by runningman84** [fluxcd/terraform-provider-flux#95] opened 2021-02-11 15:56 UTC
I have tried to setup flux using the sample config in the Readme.md. Is there any solution to run this setup without -target?

```
Error: Invalid for_each argument
  on .terraform/modules/eks.flux/main.tf line 38, in resource "kubectl_manifest" "apply":
  38:   for_each   = { for v in local.apply : lower(join("/", compact([v.data.apiVersion, v.data.kind, lookup(v.data.metadata, "namespace", ""), v.data.metadata.name]))) => v.content }
The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
Error: Invalid for_each argument
  on .terraform/modules/eks.flux/main.tf line 66, in resource "kubectl_manifest" "sync":
  66:   for_each   = { for v in local.sync : lower(join("/", compact([v.data.apiVersion, v.data.kind, lookup(v.data.metadata, "namespace", ""), v.data.metadata.name]))) => v.content }
The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

**Comment by mvaal** [comment] 2021-02-11 17:57
We are seeing the same thing, came to post the same issue.
It looked to be caused by this PR
https://github.com/fluxcd/terraform-provider-flux/pull/85/files
but we tried to revert to the review prior to that and still see the same error.

**Comment by phillebaba** [comment] 2021-03-01 20:04
This is not an issue with the provider but rather a limitation of Terraform right now. It is not possible to iterate a computed value which is derived from a resource which in turn takes a computed value as an input. You are probably using the computed git repo url as an input to the flux data source right?

**Comment by tehlers320** [comment] 2021-03-17 14:25
This was the simple fact that modules cannot use data resources, not now and not ever. The only way for a module in terraform to use a data resource is as an output for your main terraform. 

The ongoing debate if this will ever be fixed in terraform is [here](https://github.com/hashicorp/terraform/issues/4149). 

Until then, do not use this provider from within a module. It goes in your main terraform. 

This can be closed.

**Comment by stefanprodan** [comment] 2021-03-17 14:34
Closing this as it's not something we ca fix, thanks @tehlers320 for the explanation.

**Closed by stefanprodan** 2021-03-17 14:34 UTC

**Comment by spiegela** [comment] 2021-06-12 04:08
I managed to get Flux deployed within a module using this alternate snippet:

```terraform
data "kubectl_file_documents" "install" {
  content = data.flux_install.this.content
}

resource "kubectl_manifest" "install" {
  for_each           = toset(data.kubectl_file_documents.install.documents)
  yaml_body          = each.value
  override_namespace = var.flux_namespace
}

data "kubectl_file_documents" "sync" {
  content = data.flux_sync.this.content
}

resource "kubectl_manifest" "sync" {
  for_each           = toset(data.kubectl_file_documents.sync.documents)
  yaml_body          = each.value
  override_namespace = var.flux_namespace
}

```
