### ISSUE TITLE
Installing flux manifests from a different source?

### ISSUE THREAD

**Issue by smills24** [fluxcd/terraform-provider-flux#235] opened 2021-12-20 16:57 UTC
Hi there 👋 

I'm trying to use the terraform-flux-provider to install flux from manifests stored on our internal network, not on GitHub.

I see a "BaseURL" option [here in manifestgen](https://github.com/fluxcd/flux2/blob/main/pkg/manifestgen/install/options.go) that seems to do what I want, but looking at [this code](https://github.com/fluxcd/terraform-provider-flux/blob/main/pkg/provider/data_install.go) it doesn't look like it can be set in terraform and will always default to "https://github.com/fluxcd/flux2/releases". Is my interpretation correct, or is there a way to configure it to get the manifests from another source?

If not, how do you feel about adding that option? I would be happy to open a pull request.

Thank you,
Steph

**Comment by condescendent** [comment] 2022-01-10 17:30
Noted and followed.

**Comment by hiddeco** [comment] 2022-01-14 10:15
Sorry it took awhile to get to this, most of this have been enjoying time of during the holidays period. :fireworks: 

I am not the main maintainer of this repository, but I think we generally are open to a contribution which makes this configurable.
@stefanprodan @phillebaba any objections?

**Comment by condescendent** [comment] 2022-01-24 16:09
Any update about this?

**Comment by sc-joostvandencruyce** [comment] 2022-02-07 13:39
Seems duplicate of #8

**Comment by vulpine** [comment] 2022-02-08 17:26
I've written the above pull request to make this configurable - thanks for pointing out the BaseURL option @smills24 !

**Comment by darkowlzz** [comment] 2022-03-25 10:10
Implemented in #251

**Closed by darkowlzz** 2022-03-25 10:10 UTC
Labels: enhancement, area/install
