### ISSUE TITLE
Support for azure devops (git implementation)

### ISSUE THREAD

**Issue by shashken** [fluxcd/terraform-provider-flux#71] opened 2021-01-05 08:20 UTC
After https://github.com/fluxcd/source-controller/pull/213 was merged, azure devops works perfectly (thanks @phillebaba !)
But when I use this terraform provider to create a new cluster I have to manually modify the `GitRepository` crd and chand to libgit2.
Is it possible to add the gitimplementation as a variable in this TF provider?
@phillebaba @stefanprodan

**Comment by phillebaba** [comment] 2021-01-12 21:45
Sorry for the delay, I am working on a guide right now which will make sure that everything works.

The issue is that that guide will rely on me getting a PR completed for the Azure DevOps Terraform provider.
https://github.com/microsoft/terraform-provider-azuredevops/pull/225

I cant publish the guide until I get that PR merged and the provider released.

**Comment by shashken** [comment] 2021-01-13 08:59
Didn't know that repo existed so thanks! Can we have an intermediate version? Everything is working perfectly, the only think I need to do is edit the GitRepository CRD manually and change git-implementation from go-git to libgit2
I can help with the PR, but can you help me where I need to apply the change? @phillebaba

**Comment by phillebaba** [comment] 2021-01-13 22:57
@shashken yeah you are probably right, it is better to get it out so people can use the feature. Then I can add the guide as soon as that PR is merged. There is now a PR to add this option, we just need to merge the PR in fluxv2 and make a release before i can merge this PR. That should not take too long.

**Closed** 2021-01-15 13:57 UTC

**Comment by rymancl** [comment] 2021-02-17 13:34
Hey guys, is there an example setup for Azure DevOps anywhere? This may related to #8 but I'm not certain.

I'm having issues getting `flux_sync` working properly and I think it's related to authentication with the Azure DevOps repo. I was trying to go by the examples at the bottom of the README.

```terraform
data "flux_sync" "main" {
  target_path         = "infra/workloads"
  url                 = "https://myorg@dev.azure.com/myorg/myproject/_git/myrepo"
  branch              = "main"
  git_implementation  = "libgit2"
  namespace           = "my-namespace"
```
}

I'm using an `ExternalSecret` in a `kubectl_manifest` resource for my credentials in Secrets Manager. I'm just unsure what those credentials need to be. With fluxv1 I used ssh, putting my ssh key in SM, but if I use the ssh clone URL for the "url" I get
>Error: expected "url" to be a valid url, got git@ssh.dev.azure.com:v3/myorg/myproject/myrepo: parse "git@ssh.dev.azure.com:v3/myorg/myproject/myrepo": first path segment in URL cannot contain colon

So if I'm going by the example in the README
```
  data = {
    username = "git"
    password = var.flux_token
  }
```
what does the username and password need to be for Azure DevOps?
Any tips here would be great. Thanks!

**Comment by stefanprodan** [comment] 2021-02-17 13:44
Check out the Azure docs in here https://toolkit.fluxcd.io/guides/installation/#generic-git-server

**Comment by rymancl** [comment] 2021-02-17 17:32
> 
> 
> Check out the Azure docs in here https://toolkit.fluxcd.io/guides/installation/#generic-git-server

Thanks, Stefan. That helps. I've gotten a bit farther.
I've pulled some logs from source-controller which are below...

Using that `data {}` block from the README got me this error
>{"level":"error","ts":"2021-02-17T15:24:06.693Z","logger":"controller.gitrepository","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","name":"flux-system","namespace":"my-namespace","error":"auth error: invalid 'flux-system' secret data: required fields 'identity' and 'known_hosts'"}

I updated my `data {}` block to be like this, [per docs](https://toolkit.fluxcd.io/components/source/gitrepositories/#ssh-authentication):
```terraform
  data = {
    known_hosts = <<EOT
<known hosts for ssh.dev.azure.com>
EOT
    identity = <<EOT
-----BEGIN RSA PRIVATE KEY-----
<my-ssh-priv-key>
-----END RSA PRIVATE KEY-----
EOT
  "identity.pub" = "<my-ssh-pub-key>"
  }
}
```
_(These will obviously not be hard-coded once I get this working)_

Now I'm seeing this error:
>{"level":"error","ts":"2021-02-17T16:57:42.850Z","logger":"controller.gitrepository","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","name":"flux-system","namespace":"my-namespace","error":"auth error: EOF"}

I see the same error from
```
flux get sources git -A
```

Any ideas? And if you have a better place for me to ask this stuff I'm happy to do so, I just felt like it was related to the Azure DevOps support and couldn't find much info specific to Azure DevOps + Flux provider.

**Comment by samiyaakhtar** [comment] 2021-04-09 00:33
> I tracked my ssh issue down to incorrect syntax with known_hosts. I've fixed it and all seems good now. But please let me know if you see I'm doing something incorrectly.  

@rymancl I'm currently running into the exact same EOF issue and would really appreciate if you could share the syntax with `known_hosts` that worked for you. Thank you so much!

**Comment by rymancl** [comment] 2021-04-09 11:57
> 
> 
> > I tracked my ssh issue down to incorrect syntax with known_hosts. I've fixed it and all seems good now. But please let me know if you see I'm doing something incorrectly.
> 
> @rymancl I'm currently running into the exact same EOF issue and would really appreciate if you could share the syntax with `known_hosts` that worked for you. Thank you so much!


Hi @samiyaakhtar! So I was only able to get it to work with an un-hashed known_hosts file that has commented out lines removed. For example:
>ssh-keyscan gitlab.com

will give me something like 
```
# gitlab.com:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
# gitlab.com:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
gitlab.com ssh-rsa <pub-key-here>
# gitlab.com:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
gitlab.com ecdsa-sha2-nistp256 <pub-key-here>
# gitlab.com:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
gitlab.com ssh-ed25519 <pub-key-here>
# gitlab.com:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
```

My known_hosts file ended up looking like:
```
gitlab.com ssh-rsa <pub-key-here>
gitlab.com ecdsa-sha2-nistp256 <pub-key-here>
gitlab.com ssh-ed25519 <pub-key-here>
```

The same applies for other known hosts I wanted to add.

As a side note: I believe I also wasn't able to have a newline at the end of the known_hosts file, IIRC.
