### ISSUE TITLE
ignore_changes does not work for lifecycle repository_files

### ISSUE THREAD

**Issue by pavel-trubitsyn** [fluxcd/terraform-provider-flux#530] opened 2023-08-01 11:04 UTC
Engineers want to edit kustomization.yaml directly in repo, but tf will override changes on next apply. 
I tried to use lifecycle with ignore_changes, but it looks like does not work.

`lifecycle {
    ignore_changes = [ repository_files ]
 }`

In my case, I want to bootstrap cluster without overriding kustomization.yaml. Also, i tried kustomization_override option, but it will override changes on next apply too.

Is it possible to ignore changes in kustomization.yaml?

**Comment by cablespaghetti** [comment] 2023-08-16 08:15
Having the same issue. There has to be _some_ way of bootstrapping once and ignoring changes from then on...

**Comment by lodotek** [comment] 2023-09-11 22:50
➕ 1️⃣  same here.

**Comment by ycyr** [comment] 2023-10-27 15:16
Any update on this issue ?

**Comment by xsvil** [comment] 2024-01-03 02:38
Seems like it's still not fixed in the latest provider version. Any ETA?

**Comment by swade1987** [comment] 2024-03-29 12:46
Hello @pavel-trubitsyn ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Comment by swade1987** [comment] 2024-04-09 17:04
Closing as duplicate of https://github.com/fluxcd/terraform-provider-flux/issues/477, the recommended approach is described in that issue.

**Closed by swade1987** 2024-04-09 17:04 UTC
