### ISSUE TITLE
flux_install and flux_sync deprecation date

### ISSUE THREAD

**Issue by mkkot-onegini** [fluxcd/terraform-provider-flux#534] opened 2023-08-08 12:55 UTC
Hello,

> The datasources flux_install and flux_sync are deprecated, with a warning about their removal in the future. 

Is there some timeline for the deprecation? Those resources were removed from provider's documentation but they keep working. I'm asking because for our systems it's going to be a big change, so we would like to prepare for it. Just not sure if we have to prepare now.

**Comment by stefanprodan** [comment] 2023-09-04 15:35
@alialperak the `flux_bootstrap_git` resource is GA, it  uses the same code as `flux bootstrap` and does the same thing: installs, upgrades or reconfigures Flux.

For Flux, Terrafrom state has no value, as Flux knows how to manage itself from Git, it detects changes in its configuration and corrects drift.

**Comment by alialperak** [comment] 2023-09-04 15:42
> @alialperak the `flux_bootstrap_git` resource is GA, it  uses the same code as `flux bootstrap` and does the same thing: installs, upgrades or reconfigures Flux.
> 
> 
> 
> For Flux, Terrafrom state has no value, as Flux knows how to manage itself from Git, it detects changes in its configuration and corrects drift.  

@stefanprodan I would expect it to detect changes on cluster and apply if anything drifts or overwrite but after first bootstrap nothing is applied on cluster. flux bootstrap via cli works fine for me. For example I can't upgrade flux version via this terraform module using flux_bootstrap_git, may be I am missing something I will double check but I have seen some other people having issues on an another issue. I have to remove state from statefile and reapply terraform and it works ok.

**Comment by stefanprodan** [comment] 2023-09-04 15:49
We test the upgrade here: https://github.com/fluxcd/terraform-provider-flux/blob/4771d1417b3fcb248fc0d42bd7e2f05929bb1dd4/internal/provider/resource_bootstrap_git_test.go#L227-L250

If upgrade doesn't work for you, please open an issue with an example that we can replicate.

**Comment by swade1987** [comment] 2024-03-29 12:42
Hello @mkkot-onegini  ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Comment by stefanprodan** [comment] 2024-04-03 12:11
Both `flux_install` and `flux_sync` will be removed in the next release Flux v2.3 in Q2.

**Closed by stefanprodan** 2024-04-03 12:11 UTC
