### ISSUE TITLE
Public path with manifests

### ISSUE THREAD

**Issue by jvkubjg** [fluxcd/terraform-provider-flux#529] opened 2023-08-01 09:20 UTC
Provider Version: 1.0.1

Since we are working on private network, I am setting up private docker registry like that:

```
resource "flux_bootstrap_git" "this" {
  path = "some-path"
  registry = private.registry.io/fluxcd/
}
```
We also proxy the provider localization with terraform proxy settings
```
provider_installation {
 network_mirror {
  url = "https://private.domain/repository/terraform-proxy/v1/providers/"
  }
}
```
But Flux still wants to download manifest from the github.com, and we are getting following error (since github.com is not white-listed on our env and will never be):
```
╷
│ Error: Bootstrap run error
│ 
│   with module.k8s_operations.flux_bootstrap_git.this,
│   on .terraform/modules/k8s_operations/flux-cd.tf line 1, in resource "flux_bootstrap_git" "this":
│    1: resource "flux_bootstrap_git" "this" {
│ 
│ component manifest generation failed: failed to download manifests.tar.gz
│ from
│ https://github.com/fluxcd/flux2/releases/download/v2.0.1/manifests.tar.gz,
│ error: Get
│ "https://github.com/fluxcd/flux2/releases/download/v2.0.1/manifests.tar.gz":
│ Forbidden
```

**Expected behavior:** 
Adding optional attribute like:
`manifest_url` that will specify the path for the manifests

**Comment by swade1987** [comment] 2024-03-29 12:47
Hello @jvkubjg  ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Comment by swade1987** [comment] 2024-04-09 17:03
@jvkubjg you need to use the `manifest_path` variable in the `flux_bootstrap_git` resource to specify where you want the manifests to be taken from. 

I would propose to download them from [here](https://github.com/fluxcd/flux2/releases/download/v2.2.3/manifests.tar.gz) into your terraform module and then reference the `tar.gz` with a relative path in the `manifest_path`

**Comment by swade1987** [comment] 2024-04-22 16:19
I am closing this issue due to over 3 weeks of inactivity. 
If you feel that the issue should not have been closed, you can always open a new issue.

**Closed by swade1987** 2024-04-22 16:19 UTC
Labels: request for feedback
