### ISSUE TITLE
Both Terraform and Flux manging Flux leads to clumsy situations

### ISSUE THREAD

**Issue by ltdeoliveira** [fluxcd/terraform-provider-flux#176] opened 2021-07-07 21:50 UTC
Hello,

My team currently uses Terraform to deploy the Flux v1 Helm chart. We're investigating how to migrate to Flux v2 without deviating too much from the current approach. We have done some experimentation with this provider, but there are some areas where we would like to request improvements, and/or get guidance on how to deal with them.

Following the advice in #146 , we removed the commit of the `kustomization.yaml` file, and then committed our own `kustomization.yaml`. Every time we run a `terraform apply`, the non-customized configuration is applied for a brief period until Flux reconciles and applies the customized configuration. This is the same problem related by @glerchundi in #120, and this drift is not ideal for us, as we customize a lot of Flux configs, specially K8S-related.

The ideal situation for us would be to completely manage Flux with Terraform, not depending on Flux configuring itself via manifests. I understand that this would require all parameters to be available via Terraform. Do you guys are planning on addressing that? Is there any other way we aren't seeing to fully manage Flux with Terraform?

**Comment by phillebaba** [comment] 2021-07-08 12:42
So regarding the plan changes caused by differences in the cluster content and manifest content, that is something weird as I have not seen this. I have been using my own kustomization file to override the priorityclass for a while now without any issues. Could you share the Terraform config that you are using to install Flux?

Your second question touches on a much larger topic related to how Terraform and Kubernetes work together. This provider was built as it was the only good option out there to allow installation of Flux with Terraform. Helm was not really an option, mostly because it does not deal with CRD updates, but also because it would have to be maintained by someone. There are works going to with for example hashicorp/terraform-provider-kubernetes-alpha to make management of CRDs with Terraform easier but it really is not production ready yet.

**Comment by ltdeoliveira** [comment] 2021-07-12 20:38
Hello @phillebaba , thanks for the detailed answer about my second point.

About the first one, I'm using the configuration from this provider's docs: https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/github

I'll try to better explain the problem:

1 - I run `terraform apply` without the `resource "github_repository_file" "kustomize"` block. Flux is created, gotk-sync and gotk-components are committed to the repo
2 - I commit a `kustomization.yaml` and gotk-patches files to the repo, Flux applies my desired changes
3 - I run `terraform apply`  again, Terraform looks at the differences in the gotk-sync and gotk-components manifests and applies the original configuration **in the cluster**, so **I have the undesired original configuration applied until Flux reconciles again**
4 - Flux reconciles and applies my desired configuration

The end-state might be the desired, but just as an example, I don't want my node selectors or tolerations changing this way. 

We have someone working on a possible workaround: doing this bootstrap only once via Terraform, and then configuring Flux only via gitops. It's not what we want, and we still have some validations to do, but it might be the only path for now.

**Comment by phillebaba** [comment] 2021-07-12 20:51
@ltdeoliveira could you have a look at #178 and tell me if that would solve your Kustomize problems? :smiley:

**Comment by gvillafanetapia** [comment] 2021-11-16 21:50
Hi! 
I'm having similar issues.. I don't see how #178 solves this clashes between terraform state and flux 🤔 

We are commiting the kustomization and gotk files from terraform to the repo and flux seems to eventually change some things, which terraform in turn will try to adapt to its state.

The only workaround we could think of was adding;

```
lifecycle {
    ignore_changes = [content]
  }
```

Is there a better option?

Thank you!

**Comment by neillturner** [comment] 2021-12-01 16:38
https://github.com/fluxcd-community/helm-charts i'm found these work ok and i suppose you could call from terraform -)

**Comment by gvillafanetapia** [comment] 2021-12-01 18:19
🤔 and deploy it from terraform with helm provider?

**Comment by ulrichwinter** [comment] 2022-10-20 08:58
I think, this question is still open somehow.
So currently, we need to distinguish between the initial bootstrapping of flux in a given cluster and its ongoing management.
If the ongoing management of flux is done by flux itself, then the terraform approach of managing every resource it initially created for the resources complete lifetime results in this conflict: one resource (the flux operator) is managed by two different tools.

To avoid this, I see the following approaches:
1. use terraform only for the initial bootstrapping of flux. This can be done using the `lifecycle {ignore_changes = [all]}` approach as mentioned by @gvillafanetapia .
2. do the initial bootstrapping manually, e.g. using `flux install ...`. 

Downsides:
for 1.: there may be some interference, e.g. when the flux_install resource is removed from terraform
for 2.: manual process instead of IaC may lead to manual errors when setting up a new cluster

So my question is: is this true, or did I miss something?

**Comment by Just-Insane** [comment] 2023-03-22 00:23
I also have this question and haven't been able to find an answer.

My current solution for this has been to break out parts of my repository into Terraform managed `flux-system` configuration, and flux managed `flux` configuration, as seen below:

```
$ tree <repo>/kubernetes

├── flux
│   ├── kustomization.yaml
│   └── repositories
│       ├── git
│       │   ├── flux-monitoring.yaml
│       │   └── kustomization.yaml
│       ├── helm
│       │   ├── kustomization.yaml
│       │   └── metallb.yaml
│       └── kustomization.yaml
└── flux-system
    ├── README.org
    ├── gotk-components.yaml
    ├── gotk-sync.yaml
    └── kustomization.yaml
```

While this seems to work (so far, this is only my first week of using Terraform/Flux), it is (imo) messy and cumbersome. For example, the README file was generated by hand making note that `flux-system` is managed by Terraform, is non-persistent, and Flux configuration should be put in `flux`.

The other solution I attempted was to set the `target_path` in Terraform to something like `kubernetes/flux<-system>`, however, this seemed to make it very difficult to add a GitRepository for `kubernetes/apps`, as I was unsure how to persistnetly modify the `kubernetes/flux<-system>/kustomization.yaml` file to include a repository for the `kubernetes` folder (and this would have likely caused somewhat of a loop).

**Comment by swade1987** [comment] 2024-03-24 16:02
@ltdeoliveira I hope you've successfully managed to migrate to v2 using the provider. If so, are you happy for me to close this issue?

**Comment by swade1987** [comment] 2024-04-01 13:10
Hi @ltdeoliveira  👋

I hope you are doing well! As part of our ongoing effort to maintain and improve the quality of our project, I've been reviewing open issues and came across the one you've reported. First off, thank you for taking the time to contribute by reporting this issue; your input is crucial to us.

Upon reviewing the details of your issue, I noticed that it involves the use of a resource or feature that has yet to be supported since the 1.0.0 release of our project, which was approximately 9 months ago. This might be a key factor in the challenges you're experiencing. We understand that changes and deprecations can impact your work, and we're here to help navigate these transitions. If there are specific reasons you've continued using this unsupported resource or if there's any way we can assist in migrating to a supported alternative, please let us know.

Additionally, to ensure the efficient management of our issue tracker and to focus on issues that are actively affecting our community, we have implemented a policy for issues that remain inactive. If there is no activity on this issue within the next 3 weeks, we will consider the issue inactive and close it for you. This doesn't mean your issue is not important to us, but rather that we aim to keep our focus on actively pursued concerns. Of course, if the issue continues or if you have further updates in the future, feel free to reopen the issue or create a new one.

Thank you once again for your contribution to our project. Your feedback not only helps us improve but also supports the broader community in overcoming similar challenges. We look forward to hearing from you and hope to resolve any outstanding concerns together.

Best regards,

Steve

**Comment by swade1987** [comment] 2024-04-09 10:48
> I also have this question and haven't been able to find an answer.
> 
> My current solution for this has been to break out parts of my repository into Terraform managed `flux-system` configuration, and flux managed `flux` configuration, as seen below:
> 
> ```
> $ tree <repo>/kubernetes
> 
> ├── flux
> │   ├── kustomization.yaml
> │   └── repositories
> │       ├── git
> │       │   ├── flux-monitoring.yaml
> │       │   └── kustomization.yaml
> │       ├── helm
> │       │   ├── kustomization.yaml
> │       │   └── metallb.yaml
> │       └── kustomization.yaml
> └── flux-system
>     ├── README.org
>     ├── gotk-components.yaml
>     ├── gotk-sync.yaml
>     └── kustomization.yaml
> ```
> 
> While this seems to work (so far, this is only my first week of using Terraform/Flux), it is (imo) messy and cumbersome. For example, the README file was generated by hand making note that `flux-system` is managed by Terraform, is non-persistent, and Flux configuration should be put in `flux`.
> 
> The other solution I attempted was to set the `target_path` in Terraform to something like `kubernetes/flux<-system>`, however, this seemed to make it very difficult to add a GitRepository for `kubernetes/apps`, as I was unsure how to persistnetly modify the `kubernetes/flux<-system>/kustomization.yaml` file to include a repository for the `kubernetes` folder (and this would have likely caused somewhat of a loop).

@Just-Insane I think you may find https://github.com/swade1987/flux2-multi-cluster-bootstrap-repo useful. It's the way I structure the initial bootstrap repo per cluster.

**Comment by ulrichwinter** [comment] 2024-04-10 19:25
This problem is solved for us.
We are bootstrapping flux with the terraform resource flux_bootstrap_git provided by "fluxcd/flux" currently using version "~> 1.2.0".

**Closed** 2024-04-16 06:25 UTC
Labels: area/docs, request for feedback
