### ISSUE TITLE
Missing property name in data_sync

### ISSUE THREAD

**Issue by phenixdotnet** [fluxcd/terraform-provider-flux#40] opened 2020-11-12 14:40 UTC
Hello,
In the README, the `data_sync` data is used to populate the secret `metadata.name` property but the `name` property [doesn't exists in the resource](https://github.com/fluxcd/terraform-provider-flux/blob/main/pkg/provider/data_sync.go#L101)

As per the code the name is the namespace which is IMO strange. I can push a PR to add the name property in `data_sync` resource with a default to `namespace` value or as a calculated property if you're ok with that.

Thanks

**Comment by stefanprodan** [comment] 2020-11-12 15:46
>  I can push a PR to add the name property in data_sync resource with a default to namespace value or as a calculated property if you're ok with that.

That would be great! Thanks @phenixdotnet

**Comment by phillebaba** [comment] 2020-11-12 16:08
I think there is some confusion around this issue. The problem is actually in the README docs rather than a missing parameter. Have a look at the guide where this has been fixed.
https://github.com/fluxcd/terraform-provider-flux/blob/c0056e61ff8df2427c9ef696535e2fb284613469/examples/github/main.tf#L88

The reason it just sets the name to the namespace is to align the functionality with the bootstrap CLI.
https://github.com/fluxcd/flux2/blob/10711ed780d7e96f943cbf71bb01877261fb4438/cmd/flux/bootstrap_github.go#L262

Instead I think we should just fix the docs in the README to align with the guides.

I am sorry for the confusion @phenixdotnet :heart:

**Comment by phenixdotnet** [comment] 2020-11-12 16:12
ah ah no probs :)

But in fact using the default value as `syncDefaults.Namespace` keep the default CLI behavior but allow the user to configure the resources name if required. 
It's a bit strange to not have access to the `name` property no ?

**Comment by phillebaba** [comment] 2020-11-12 16:15
After reading my own comment again I came to the same conclusion you did. That it actually would not be a bad thing to expose the name property as long as it defaults to the namespace value.

I am fine with adding this, @stefanprodan what do you think?

**Comment by stefanprodan** [comment] 2020-11-12 16:23
@phillebaba I'm for adding the name property, in the future we could allow people to use `data_sync` for more than just bootstrap.

**Comment by phillebaba** [comment] 2020-11-15 18:56
Closing as the issue has been fixed in PR #41.

**Closed by phillebaba** 2020-11-15 18:56 UTC
Labels: bug
