### ISSUE TITLE
fluxcd_bootstrap_git does not re-create flux-system secret

### ISSUE THREAD

**Issue by ketbla** [fluxcd/terraform-provider-flux#566] opened 2023-10-23 13:46 UTC
We've been using fluxcd and it works great, however now we're trying to rotate secrets and that seems to be broken with terraform.

According to the guide https://fluxcd.io/flux/installation/configuration/deploy-key-rotation/ we are supposed to:
1. Delete secret in flux-system
2. Re-run fluxcd bootstrap to re-create it

However when using terraform resource fluxcd_bootstrap_git, it does not detect that the secret was deleted and does not re-create it.

Steps to reproduce:
1. run `kubectl delete secret flux-system -n flux-system
2. Re-run terraform
3. No changes, infrastructure up to date

Because of this, it makes it impossible to rotate keys for people using terraform to bootstrap fluxcd.

**Comment by knutgoetz** [comment] 2023-11-02 22:42
You are right, the provider will not detect any diff and create a new secret since it does not really know about it.
All the provider does is performing  something similar to a  `flux bootstrap` run with a specific set of parameters and it should detect any drift if you change some attributes of the provider or the resource. As a workaround you could

1. Mange the secret seperatly with terraform, something like should do the trick (using the kubernetes provider):
```
resource "tls_private_key" "flux_github_deploy_key" {
  algorithm     = "ECDSA"
  ecdsa_curve = "P256"
}

resource "kubernetes_secret" "flux_system_ssh" {
  metadata {
    name           = "flux-system"
    namespace = "flux-system"
  }

  data = {
    known_hosts  = var.github_kown_hosts
    identity            = tls_private_key.flux_github_deploy_key[0].private_key_pem
    "identity.pub" = tls_private_key.flux_github_deploy_key[0].public_key_openssh
  }
}

resource "flux_bootstrap_git" "this" {
  ...
  
  disable_secret_creation  = true
  secret_name                     = kubernetes_secret.flux_system_ssh[0].metadata[0].name
}
```
2. try deleting the resource from your terraform state and reapply. Since `flux bootstrap` is idempotent it should work. Havn't tested this approach though :)

Take this advice with a grain of salt, though. I'm not an expert FluxCD.

**Comment by swade1987** [comment] 2024-03-29 11:42
@ketbla @mloskot 

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are handled promptly and efficiently.

I noticed this issue you reported, and I wanted to check in to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, please share how it was fixed. This information could be incredibly helpful to others in the community facing similar problems and would allow us to close this issue with a clear resolution.

If the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. I look forward to hearing from you!

Steve

**Comment by swade1987** [comment] 2024-03-29 12:25
@ketbla @mloskot 

I have also created https://github.com/swade1987/flux2-multi-cluster-bootstrap-repo which you may find useful. It's an example of how you can bootstrap multiple clusters from the same initial bootstrap repository.

**Comment by mloskot** [comment] 2024-04-02 12:28
> @knutgoetz This is a good piece of advice, but I'm wondering how the `flux_bootstrap_git` will behave about the pre-existing `flux-system` namespace, especially if one wants to bootstrap Flux on clean slate but with the secret pre-existing
> 
>     1. Create `flux-system` namespace
>     2. Create Git sync credentials secret in `flux-system` namespace
>     3. Create `flux_bootstrap_git` resource with `secret_name` referring to the secret create in step 2.
> 
> I'm yet to try this scenario myself.

I have tried this scenario and everything works well for me, so I stick to the following process of bootstrapping Flux with Terraform:

```hcl
resource "kubernetes_namespace" "flux" {
  metadata {
    name = local.flux_namespace
    annotations = merge(local.global_kubernetes_annotations, {
      "kustomize.toolkit.fluxcd.io/prune" = "disabled"
    })
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "flux_bootstrap_git" "flux" {
  namespace = kubernetes_namespace.flux.metadata[0].name
  path      = local.flux_bootstrap_path
  version   = "v2.1.2" # explicit to trigger update on demand
  ...
}
```

Thanks @swade1987 for chiming in.

**Comment by swade1987** [comment] 2024-04-22 16:27
@ketbla @knutgoetz @mloskot I created https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/github-self-managed-ssh-keypair a few weeks ago which I think you guys may find useful to solve this issue.

**Comment by swade1987** [comment] 2024-04-23 10:39
> @ketbla @knutgoetz @mloskot I created https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/github-self-managed-ssh-keypair a few weeks ago which I think you guys may find useful to solve this issue.

The example above shows the recommended approach to get around this issue. Closing this issue.

**Closed by swade1987** 2024-04-23 10:39 UTC

**Comment by apshoemaker** [comment] 2024-08-08 17:59
May I recommend that this be re-opened or perhaps a feature request could be created requesting 2 things:

Firstly, that [this](https://github.com/fluxcd/terraform-provider-flux/blob/main/internal/provider/resource_bootstrap_git.go#L530) be handled properly and not subject to workaround.

Secondly, that user documentation be updated universally to point out this foot-gun since it's kind of a big one (particularly for those of us in the gov't sector that have specific rules around regular key rotation).  As an example, your official Gitlab example [here](https://github.com/fluxcd/terraform-provider-flux/blob/main/examples/gitlab-via-ssh/main.tf) makes no mention of the issue nor do the docs (to my perusal) on the Terraform Provider main page [here](https://registry.terraform.io/providers/fluxcd/flux/latest/docs).

I'm happy to contribute in whatever capacity makes sense (docs, design talks regarding reconciliation, etc).  Let me know if it is more helpful to open a follow up issue rather than re-opening this one or how best to proceed.
