### ISSUE TITLE
Terraform Apply fails with "for_each" value cannot be determined until apply

### ISSUE THREAD

**Issue by vara-bonthu** [fluxcd/terraform-provider-flux#242] opened 2022-01-23 14:38 UTC
Hi 

I am trying to install flux using this provider example and I am hitting the following error when i run `terraform apply` 

```╷
│ Error: Invalid for_each argument
│ 
│   on ../../../modules/kubernetes-addons/fluxcd/main.tf line 15, in resource "kubectl_manifest" "apply":
│   15:   for_each   = { for v in local.install : lower(join("/", compact([v.data.apiVersion, v.data.kind, lookup(v.data.metadata, "namespace", ""), v.data.metadata.name]))) => v.content }
│     ├────────────────
│     │ local.apply will be known only after apply
│ 
│ The "for_each" value depends on resource attributes that cannot be determined until apply,
│ so Terraform cannot predict how many instances will be created. To work around this, use
│ the -target argument to first apply only the resources that the for_each depends on.
```

I think the issue is with this block where for_each value cannot be determined until apply.  Am i missing something? 

```hcl
locals {
  install = [ for v in data.kubectl_file_documents.install.documents : {
    data: yamldecode(v)
    content: v
  }
  ]
}
# Apply manifests on the cluster
resource "kubectl_manifest" "apply" {
  for_each   = { for v in local.install : lower(join("/", compact([v.data.apiVersion, v.data.kind, lookup(v.data.metadata, "namespace", ""), v.data.metadata.name]))) => v.content }
  depends_on = [kubernetes_namespace.flux_system]
  yaml_body = each.value
}
```

Here is my Terraform version
```sh
▶ terraform version 
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/fluxcd/flux v0.9.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/aws v3.73.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
```

It would be really good if we have a Helm Chart for deploying the Flux V2.

**Comment by mwalczykpl** [comment] 2022-01-31 15:55
Hi I had the same issue, but my module bootstrapping Fluxcd had dependency to other module (creating cluster). After removing dependency (and creating cluster in another module) error didn't show again.
```
#resource "null_resource" "kind-cluster" {
#  provisioner "local-exec" {
#    command = "kind create cluster --name ${var.application_name}"
#  }
#}

module "flux-bootstrap" {
  source = "../modules/flux-bootstrap"
  branch = "main"
  deploy_key_name = "${var.application_name}-deployment"
  github_owner = var.github_owner
  repository_name = var.application_name
  target_path = "clusters/development"
#  depends_on = [null_resource.kind-cluster]
}
```

**Comment by mike-morr** [comment] 2022-02-17 14:14
How do we make our custom flux module wait for the cluster to be built if we can't use `depends_on` in the module definition?

**Comment by vara-bonthu** [comment] 2022-02-17 16:54
I would prefer Helm chart to deploy **Flux V2** over these manifests. 

I came across this one https://github.com/fluxcd-community/helm-charts. Looking forward to try this one

**Comment by bravecobra** [comment] 2022-08-15 06:50
I'm hitting the same issue. You cannot have locals depend on data sources in terraform as data sources are only read upon apply. Thus `terraform plan` will always fail. These examples are flawed when used in a module.

**Comment by bravecobra** [comment] 2022-08-21 17:45
The relevant documentation why this fails, is explained here: https://www.terraform.io/language/meta-arguments/for_each#limitations-on-values-used-in-for_each

**Comment by sytgj7896321** [comment] 2022-09-22 17:27
I think it can be solve by null_resource
```
module "foo" {
   ... 
)

resource "null_resource" "bar" {
  triggers = {
    some_output = module.foo.some_output
  }
}

module "flux" {
  ...
  some_parameter = null_resource.bar.triggers.some_output
}
```

**Comment by leosunmo** [comment] 2022-11-16 13:12
That `null_resource` trick doesn't seem to work for me. I'd love a workaround for this!

**Comment by Sokratis1904** [comment] 2023-02-13 21:34
+1

**Comment by swade1987** [comment] 2024-03-29 14:44
Hello @vara-bonthu,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Closed** 2024-04-01 14:16 UTC
