### ISSUE TITLE
Getting Value Conversion error when pass "kubernetes" schema from the caller side

### ISSUE THREAD

**Issue by smeeklai** [fluxcd/terraform-provider-flux#472] opened 2023-05-16 11:23 UTC
Hi. I would like to define `kubernetes` schema on the caller (live) side and pass to the module. However, I got `Value Conversion` error as shown below:
```
Error: Value Conversion Error
│
│   with module.flux.provider["registry.terraform.io/fluxcd/flux"],
│   on ../../../modules/flux/main.tf line 19, in provider "flux":
│   19:   kubernetes = var.flux_kubernetes
│
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│
│ Received unknown value, however the target type cannot handle unknown values. Use the corresponding `types` package type or a custom type that handles unknown values.
│
│ Path: kubernetes
│ Target Type: *provider.Kubernetes
│ Suggested Type: basetypes.ObjectValue
```

On the caller side, I declare:
```
flux_kubernetes = {
  config_path = "~/.kube/config"
  config_context = "docker-desktop"
}
```

On the module, I do:
```
provider "flux" {
  kubernetes = var.flux_kubernetes
  ...
}
```

This is `variables.tf`
```
variable "flux_kubernetes" {
  type = any
}
```

Not sure does this suppose to work or I might miss something?

**Comment by phillebaba** [comment] 2023-05-17 20:37
Which version of the provider are you using?

**Comment by swade1987** [comment] 2024-03-29 13:06
Hello @smeeklai ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Closed** 2024-04-01 14:46 UTC
