### ISSUE TITLE
Allow use of existing namespace

### ISSUE THREAD

**Issue by ba-work** [fluxcd/terraform-provider-flux#516] opened 2023-07-10 13:39 UTC
I want to be able use an existing namespace **without** the `flux_bootstrap_git` taking it over.

Currently I can use an existing secret and an existing namespace (obviously, the secret has to be _somewhere_), but then the bootstrap resource takes over the namespace and on destroys (from taints/changes/`destroy`s/etc), it wipes out the secret (since its in the namespace).

This behavior also makes the bootstrap resource incompatible with `lifecycle { create_before_destroy = true }` since the destroy afterwards also wipes out the entire namespace.

I think something like `existing_namespace = true` would be sufficient. 

It could also be argued that this behavior should happen in cases of `disable_secret_creation = true` since the secret must exist in the same namespace.

example tf that i'm using:
```hcl
resource "tls_private_key" "flux" { algorithm = "RSA" }

resource "kubernetes_namespace" "flux" {
  metadata { name = "flux-system" }
  lifecycle { ignore_changes = [metadata[0].labels] } # have to ignore labels that flux adds
}

resource "kubernetes_secret" "flux" {
  metadata {
    name      = "flux-system"
    namespace = kubernetes_namespace.flux.metadata[0].name
  }
  data = {
    "identity"     = tls_private_key.flux.private_key_pem
    "identity.pub" = tls_private_key.flux.public_key_openssh
    "known_hosts"  = var.repository.ssh_host_key
  }
}

resource "flux_bootstrap_git" "bootstrap" {
  path                    = "flux/clusters/${var.cluster_name}"
  disable_secret_creation = true
  
  # i want this
  # existing_namespace = true
}
```

**Comment by ba-work** [comment] 2023-07-10 13:47
Current workaround for me is to carefully, `tf state rm flux_bootstrap_git.bootstrap` when appropriate, then `tf apply`.

**Comment by swade1987** [comment] 2024-03-29 12:51
Hello @ba-work  ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

---

Note: I would highly recommend letting `flux_bootstrap_git` to use the `flux-system`. You may find [this](https://github.com/swade1987/flux2-multi-cluster-bootstrap-repo ) repository useful to you. It's an example of how I have managed the bootstrapping of clusters previously by dropping any additional resources into a `flux-bootstrap` cluster which flux then reconciles.

**Comment by ba-work** [comment] 2024-04-09 12:55
That is what I'm doing. 

The example I give is using the `flux-system` namespace, the root of the problem is that `flux_bootstrap_git` takes ownership of the namespace (ie. a `tf destroy` deletes the namespace) which logically conflicts with the option of `disable_secret_creation = true` since the secret must exist in that very same namespace.

I'm just asking for way to tell the provider not to own the namespace, similar to how it has an option not to own the secret.

**Comment by swade1987** [comment] 2024-04-09 13:26
@ba-work

In my opinion (and how I have set it up in the past), I let `flux_bootstrap_git` manage the `flux-system` namespace and deploy the flux pods and the secret it requires to speak to your git repository.

Then, in the git repository, I deploy the remainder of my resources into a new namespace called `flux-bootstrap`.

I have a full example of this available [here](https://github.com/swade1987/flux2-multi-cluster-bootstrap-repo), and I think it may help you.

The sections that will be of interest to you are:

- https://github.com/swade1987/flux2-multi-cluster-bootstrap-repo/blob/main/terraform/main.tf#L65-L90
- https://github.com/swade1987/flux2-multi-cluster-bootstrap-repo/tree/main/kustomize/_base/gitrepositories

**Comment by ba-work** [comment] 2024-04-09 13:39
That's fine, but right now the provider allows you pre create a secret in the namespace, my example in the report is the smallest possible using tf. In a more productionized env (and indeed in my real uses case) its more complex and there are more "things" in the ns; having this resource secretly take over the ns (and by extension the pre created secret) is not good!

Regardless of how you've done it in the past, this is a bug/issue. Perhaps instead we should be discussing the **removal** of `disable_secret_creation`?

**Comment by ba-work** [comment] 2024-04-09 14:24
If you are that adamant, then I guess the only question I have is: What is the appropriate way to use `disable_secret_creation = true`?
I must be misunderstanding its purpose since if I use it in any capacity, doing following results in an error:
```bash
tf apply -auto-approve && tf destroy -auto-approve && tf apply -auto-approve;
```
(the second apply won't work since the destroy will have deleted the secret that it shouldn't be touching.)

**Comment by swade1987** [comment] 2024-04-09 15:27
@ba-work I use that to manage the lifecycle of the SSH keypair that flux uses to talk to your initial git repository **in Terraform** rather than let flux manage it. If you need to rotate the key then its best to use this, I actually have an example of how to use it [here](https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/github-self-managed-ssh-keypair)

**Comment by ba-work** [comment] 2024-04-09 16:11
... that linked example looks exactly like the example I wrote in the initial report. I feel like you haven't extensively used your own example otherwise you would eventually encounter the behaviour I'm talking about. I only opened the issue _because_ this resource **deleted the namespace and secret** in an environment I have with basically the same syntax.

Feel free to close issue, we are going in circles and I've migrated to just installing flux with a `null_resource` and bash script for almost a year at this point.

**Closed** 2024-04-09 16:19 UTC
Labels: request for feedback
