### ISSUE TITLE
Terraform fails to import flux_bootstrap_git 

### ISSUE THREAD

**Issue by anupclouddevops** [fluxcd/terraform-provider-flux#554] opened 2023-09-19 22:10 UTC
I am getting the below error while importing flux_bootstrap_git resource into terraform state

╷
│ Error: Could not get GitRepository flux-system/flux-system
│ 
│ failed to get API group resources: unable to retrieve the complete list of server APIs: source.toolkit.fluxcd.io/v1: the server
│ could not find the requested resource
╵

I am trying to upgrade Terraform Flux provider from 0.21.0 to 1.1.0 i.e from old bootstrap method to new bootsrap resource.

I followed the migration guide and get the above error while importing the flux_bootstrap_git resource.
My Flux controllers are on v0.37.0 and only v1beta1 and v1beta2 CRDs installed.
As per the migration guide , I kept the Flux version as it is and only upgrading terraform provider to the new bootstrap resource.
However, looks like the provider is looking for v1 CRDs which are only available in FluxCD v2.x.

I also tried downgrading Flux Client to v0.37.0 to match the server version.
$ flux version
flux: v0.37.0
helm-controller: v0.27.0
kustomize-controller: v0.31.0
notification-controller: v0.29.0
source-controller: v0.32.1

PS: I do want to upgrade FluxCD to a new version too but the migration guide suggests to upgrade the provider first and then Flux CD.

Please let me know if you need more information.

**Comment by swade1987** [comment] 2024-03-29 12:36
Hello @anupclouddevops  ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Comment by ek24014** [comment] 2024-04-12 17:06
Same issue during the migration, seems like the v1 version is not available at the time.

The error is
│ Error: Could not get GitRepository flux-system/flux-system
│
│ failed to get API group resources: unable to retrieve the complete list of server APIs: source.toolkit.fluxcd.io/v1: the server could not find the requested resource

When I review "kubectl api-resources" the v1 for sources.toolkit.fluxcd.io and kustomize.toolkit.fluxcd.io are not available. We are currently on provider 0.25.3 and flux v0.41.2

To add to this, we did additional tests and used the old way flux install and flux sync to try to deploy flux v2.1.2 with flux provider 1.1.2. In the process we got same errors

`Error: flux-system/flux-system failed to create kubernetes rest client for update of resource: resource [kustomize.toolkit.fluxcd.io/v1/Kustomization] isn't valid for cluster, check the APIVersion and Kind fields are valid
with module.flux_install.kubectl_manifest.flux_sync["/apis/kustomize.toolkit.fluxcd.io/v1/namespaces/flux-system/kustomizations/flux-system"]
on .terraform/modules/flux_install/main.tf line 284, in resource "kubectl_manifest" "flux_sync":
resource "kubectl_manifest" "flux_sync" {

Error: flux-system/flux-system failed to create kubernetes rest client for update of resource: resource [source.toolkit.fluxcd.io/v1/GitRepository] isn't valid for cluster, check the APIVersion and Kind fields are valid
with module.flux_install.kubectl_manifest.flux_sync["/apis/source.toolkit.fluxcd.io/v1/namespaces/flux-system/gitrepositorys/flux-system"]
on .terraform/modules/flux_install/main.tf line 284, in resource "kubectl_manifest" "flux_sync":
resource "kubectl_manifest" "flux_sync" {`

However, on the rerun everything goes through fine, seems like it takes time for the api version to get published.

**Comment by stefanprodan** [comment] 2024-04-16 14:48
There is no way to upgrade from 0.x to 2.x with Terraform not can you import from a cluster not on Flux v2 GA. I suggest you use the CLI to remove Flux without affecting the workloads `flux uninstall`. Then start fresh with flux_bootstrap_git.

**Closed by stefanprodan** 2024-04-16 14:48 UTC
Labels: request for feedback

**Comment by ek24014** [comment] 2024-04-24 06:04
@stefanprodan Hi,
Following your suggestion, I have uninstalled flux via CLI and rerun terraform with flux_bootstrap_git. However, I am now getting the following error:
```
│ Error: Bootstrap run error
│ 
│   with module.flux_install.flux_bootstrap_git.flux_install,
│   on .terraform/modules/flux_install/main.tf line 29, in resource "flux_bootstrap_git" "flux_install":
│   29: resource "flux_bootstrap_git" "flux_install" {
│ 
│ failed to push sync manifests: failed to push to remote: non-fast-forward
│ update: refs/heads/main
╵
Operation failed: failed running terraform apply (exit 1)
```

**Comment by stefanprodan** [comment] 2024-04-24 08:11
That's a transient error, the repo changed while terraform was running, retry it.

**Comment by ek24014** [comment] 2024-04-26 04:22
@stefanprodan The rerun did work and it seem to be consistent on each upgrade. However, when triggering terraform destroy we are running into another error
```
Error: Could not delete Flux
Unable to commit removed file(s): cannot create empty commit: clean working tree
```

**Comment by ek24014** [comment] 2024-04-26 04:57
@swade1987 Thank you the rerun seem to work constantly. However running into another issue during terraform destroy. I posted it in https://github.com/fluxcd/terraform-provider-flux/issues/479#issuecomment-2078628923
