### ISSUE TITLE
`flux_bootstrap_git` does not update components

### ISSUE THREAD

**Issue by ppodevlabs** [fluxcd/terraform-provider-flux#568] opened 2023-10-24 11:28 UTC
Hi! we are using the `flux_bootstrap_git` resource to deploy flux into our clusters.

## Description
We do have running flux into the cluster and i'm trying to update the flux components using terraform but it is not detecting any change.

Provider config
```hcl
provider "flux" {
  kubernetes = {
    host                   = data.azurerm_kubernetes_cluster.k8s_cluster.kube_admin_config.0.host
    client_certificate     = base64decode(data.azurerm_kubernetes_cluster.k8s_cluster.kube_admin_config.0.client_certificate)
    client_key             = base64decode(data.azurerm_kubernetes_cluster.k8s_cluster.kube_admin_config.0.client_key)
    cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.k8s_cluster.kube_admin_config.0.cluster_ca_certificate)
  }
  git = {
    url              = var.k8s_apps_flux_git_repository_ssh_url
    branch           = var.k8s_apps_flux_git_branch
    ssh = {
      username    = "git"
      private_key = data.secretsmanager_field.k8s_admin_sa_private_key.value
    }
  }
}
```

flux_bootstrap_git resource
```hcl
resource "flux_bootstrap_git" "cluster_manager" {
  path             = "clusters/${var.cluster_name}"
  components       = toset(var.components)
  components_extra = toset(var.components_extra)
  version          = var.flux_version
}
```

Updating the variable `flux_version` does not trigger a change.

## Expected behavior

changing the version should update the components and CRDs

**Comment by kingdonb** [comment] 2023-10-26 17:41
Did you update the Flux provider using `terraform init -upgrade`?

This is the only place I think you can go wrong, I've just tested the latest upgrade and it seems to work for me.

In my `main.tf`:

```
terraform {
  required_version = ">= 1.1.5"
  required_providers {
    flux = {
      source = "registry.terraform.io/fluxcd/flux"
      version = "1.1.2"
    }
  }
}
```

There's no need to set the `version` in `flux_bootstrap_git` resource (though setting it shouldn't hurt, it will not ensure the provider gets upgraded) - if you ensure that the provider is upgraded, it should upgrade.

My bootstrap resource looks like this without setting `version`:


```
resource "flux_bootstrap_git" "this" {
  path = "clusters/foocluster"
  components_extra = [
    "image-reflector-controller",
    "image-automation-controller"
  ]
  kustomization_override = file("${path.module}/kustomization.yaml")
}
```

**Comment by swade1987** [comment] 2024-03-29 11:40
Hello @ppodevlabs ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are handled promptly and efficiently.

I noticed this issue you reported, and I wanted to check in to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, please share how it was fixed. This information could be incredibly helpful to others in the community facing similar problems and would allow us to close this issue with a clear resolution.

If the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. I look forward to hearing from you!

Steve

**Comment by swade1987** [comment] 2024-04-09 16:49
Closing due to inactivity.

**Closed by swade1987** 2024-04-09 16:49 UTC
Labels: request for feedback
