### ISSUE TITLE
install fluxcd Error flux-system/helm-controller failed to create kubernetes rest client for update of resource

### ISSUE THREAD

**Issue by Kevinwoolworth** [fluxcd/terraform-provider-flux#187] opened 2021-08-15 11:17 UTC
I am able to create aks cluster via terraform, I want to install `fluxcd` on the cluster.  I follow this example [main.tf ](https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/install)to install fluxcd, but gave timed out error

error message:
```
kubectl_manifest.install["apps/v1/deployment/flux-system/kustomize-controller"]: Still creating... [2m0s elapsed]
kubectl_manifest.install["networking.k8s.io/v1/networkpolicy/flux-system/allow-egress"]: Still creating... [2m0s elapsed]
kubectl_manifest.install["apiextensions.k8s.io/v1/customresourcedefinition/alerts.notification.toolkit.fluxcd.io"]: Still creating... [2m0s elapsed]
kubectl_manifest.install["apiextensions.k8s.io/v1/customresourcedefinition/helmcharts.source.toolkit.fluxcd.io"]: Still creating... [2m0s elapsed]
kubectl_manifest.install["networking.k8s.io/v1/networkpolicy/flux-system/allow-webhooks"]: Still creating... [2m0s elapsed]

Error: flux-system/kustomize-controller failed to create kubernetes rest client for update of resource: flux-system/kustomize-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system failed to create kubernetes rest client for update of resource: flux-system timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {

Error: buckets.source.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: buckets.source.toolkit.fluxcd.io timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: alerts.notification.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: alerts.notification.toolkit.fluxcd.io timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: helmcharts.source.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: helmcharts.source.toolkit.fluxcd.io timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: providers.notification.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: providers.notification.toolkit.fluxcd.io timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: receivers.notification.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: receivers.notification.toolkit.fluxcd.io timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/source-controller failed to create kubernetes rest client for update of resource: flux-system/source-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/notification-controller failed to create kubernetes rest client for update of resource: flux-system/notification-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/webhook-receiver failed to create kubernetes rest client for update of resource: flux-system/webhook-receiver timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/allow-egress failed to create kubernetes rest client for update of resource: flux-system/allow-egress timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: helmrepositories.source.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: helmrepositories.source.toolkit.fluxcd.io timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/notification-controller failed to create kubernetes rest client for update of resource: flux-system/notification-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: gitrepositories.source.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: gitrepositories.source.toolkit.fluxcd.io timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: helmreleases.helm.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: helmreleases.helm.toolkit.fluxcd.io timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/source-controller failed to create kubernetes rest client for update of resource: flux-system/source-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/allow-webhooks failed to create kubernetes rest client for update of resource: flux-system/allow-webhooks timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: crd-controller-flux-system failed to create kubernetes rest client for update of resource: crd-controller-flux-system timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: kustomizations.kustomize.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: kustomizations.kustomize.toolkit.fluxcd.io timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/kustomize-controller failed to create kubernetes rest client for update of resource: flux-system/kustomize-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: crd-controller-flux-system failed to create kubernetes rest client for update of resource: crd-controller-flux-system timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/helm-controller failed to create kubernetes rest client for update of resource: flux-system/helm-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: cluster-reconciler-flux-system failed to create kubernetes rest client for update of resource: cluster-reconciler-flux-system timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/helm-controller failed to create kubernetes rest client for update of resource: flux-system/helm-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/notification-controller failed to create kubernetes rest client for update of resource: flux-system/notification-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/allow-scraping failed to create kubernetes rest client for update of resource: flux-system/allow-scraping timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {



Error: flux-system/source-controller failed to create kubernetes rest client for update of resource: flux-system/source-controller timed out fetching resources from discovery client

  on fluxcd.tf line 50, in resource "kubectl_manifest" "install":
  50: resource "kubectl_manifest" "install" {

```

I use this method to auth kubernetes
```
data "azurerm_kubernetes_cluster" "default" {
  depends_on          = [azurerm_kubernetes_cluster.default] # refresh cluster state before reading
  name                = azurerm_kubernetes_cluster.default.name
  resource_group_name = azurerm_kubernetes_cluster.default.resource_group_name
}
```

```
provider "kubectl" {}
provider "flux" {}

provider "kubernetes" {
  host                   = data.azurerm_kubernetes_cluster.default.kube_config.0.host
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.client_certificate)
  client_key             = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.cluster_ca_certificate)
}
```

terraform version : 
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.66.0"
    }
    github = {
      source  = "integrations/github"
      version = ">= 4.5.2"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0.3"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.10.0"
    }
    flux = {
      source  = "fluxcd/flux"
      version = ">= 0.0.13"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "3.1.0"
    }
  }

  required_version = ">= 0.14"
}

```

anyone can help with ?

**Comment by dzmitry-lahoda** [comment] 2021-09-24 18:19
i have azure cni:
```

│ Error: flux-system/flux-system failed to create kubernetes rest client for update of resource: resource [kustomize.toolkit.fluxcd.io/v1beta1/Kustomization] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   kubectl_manifest.sync["kustomize.toolkit.fluxcd.io/v1beta1/kustomization/flux-system/flux-system"],
│   on ..\..\modules\kubernetes\flux.tf line 109, in resource "kubectl_manifest" "sync":
│  109: resource "kubectl_manifest" "sync" {
```

**Comment by phillebaba** [comment] 2021-11-04 10:02
@dzmitry-lahoda  sorry for the late response are you still seeing these types of issues?

**Comment by dzmitry-lahoda** [comment] 2021-11-04 13:18
did not saw it

**Comment by throwawayaccount0153** [comment] 2021-11-23 17:55
@phillebaba I'm seeing this as well, I am using plain ec2, no eks.  I am using the latest flux provider 0.7.3

**Comment by Speculor** [comment] 2022-02-27 19:16
I am hitting this as well, using the model from https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/github
I used Terraform to create the EKS cluster which was successful; the flux-system namespace creation was also successful so it looks like Terraform is indeed able to authenticate to the eks cluster. The only difference I have from the above is that as I am using Terraform Cloud I have the provider configured as follows instead of using ~/.kube/config

`provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  token                  = data.aws_eks_cluster_auth.cluster.token
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
}`

**Comment by Speculor** [comment] 2022-02-27 19:17
For each of the manifest files it is returning this:

`Error: providers.notification.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: Get "http://localhost/api?timeout=32s": dial tcp 127.0.0.1:80: connect: connection refused
with kubectl_manifest.install["apiextensions.k8s.io/v1/customresourcedefinition/providers.notification.toolkit.fluxcd.io"]
on flux.tf line 100, in resource "kubectl_manifest" "install":
resource "kubectl_manifest" "install" {`

**Comment by Speculor** [comment] 2022-02-27 19:18
not sure why it's trying to localhost/api instead of the host specified in the Kubernetes provider block

**Comment by Speculor** [comment] 2022-02-27 19:29
I fixed this by updating the kubectl provider as follows:

`provider "kubectl" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  token                  = data.aws_eks_cluster_auth.cluster.token
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  load_config_file       = false
}`

**Comment by cpdeethree** [comment] 2022-03-18 23:13
> I fixed this by updating the kubectl provider as follows:
> 
> ```
> provider "kubectl" {
>   host                   = data.aws_eks_cluster.cluster.endpoint
>   token                  = data.aws_eks_cluster_auth.cluster.token
>   cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
>   load_config_file       = false
> }
> ```

I had the same problem with same error (was attempting to dial localhost) and this solution did not work for me - perhaps due to a different version of the provider.

I am using these versions:

```terraform
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.3.2"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "~> 1.11.2"
    }
```

However, the following config changes did work for me:

```terraform
provider "kubectl" {
  host  = digitalocean_kubernetes_cluster.primary.endpoint
  token = digitalocean_kubernetes_cluster.primary.kube_config[0].token
  cluster_ca_certificate = base64decode(
    digitalocean_kubernetes_cluster.primary.kube_config[0].cluster_ca_certificate
  )
}

provider "kubernetes" {
  host  = digitalocean_kubernetes_cluster.primary.endpoint
  token = digitalocean_kubernetes_cluster.primary.kube_config[0].token
  cluster_ca_certificate = base64decode(
    digitalocean_kubernetes_cluster.primary.kube_config[0].cluster_ca_certificate
  )
  config_path = "~/.kube/config"
  config_context = "name-of-context-as-defined-in-kube-config"
}```

Note the removal of load_config_file = false in the kubectl provider and the addition of config_path and config_context in kubernetes provider.

**Comment by ChrisJBurns** [comment] 2022-04-05 19:51
I had this issue for a while, but I prioritised other things as it only ever happened on cluster creation. When I re-run the Terraform it would go away. However, I've come back to this as we are testing our immutable infrastructure functionality and trying to get to a point where we are CREATE and DESTROY without problems. The destroy is problematic due to what is documented here https://github.com/fluxcd/terraform-provider-flux/issues/67. 

However that being said, I have recently updated our `azurerm` provider to latest version, same with the `kubernetes`, `flux` and `gavinbunney/kubectl` provider. 

I have changed nothing else apart from adding the `apply_retry_count` parameter, and I can confirm that 10 times out of 10, the cluster is created without the errors experienced in this issues description. Whereas before the updating of the providers and the `apply_retry_count` parameter, we would get the error in this issues description 8 times out of 10.

```yaml
# Provider used to run kubectl commands against the tooling cluster
provider "kubectl" {
  apply_retry_count      = 10
  alias = "kubectl_tools_cluster"
  load_config_file       = "false"
  host                   = module.create_kubernetes_clusters.aks_tools_host
  client_certificate     = base64decode(module.create_kubernetes_clusters.aks_tools_client_certificate)
  client_key             = base64decode(module.create_kubernetes_clusters.aks_tools_client_key)
  cluster_ca_certificate = base64decode(module.create_kubernetes_clusters.aks_tools_cluster_ca_certificate)
}
```

Our providers for brevity:
```yaml
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.0.2"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "2.9.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "1.14.0"
    }
    flux = {
      source  = "fluxcd/flux"
      version = "0.12.2"
    }
    local = {
      source  = "hashicorp/local"
      version = "2.1.0"
    }
  }
}
```

**Comment by swade1987** [comment] 2024-03-24 16:10
@Kevinwoolworth have you now resolved this issue? If so, are you happy for us to close this?

**Closed** 2024-04-01 14:15 UTC
