### ISSUE TITLE
Where to use this?

### ISSUE THREAD

**Issue by MarkLFT** [fluxcd/terraform-provider-flux#280] opened 2022-04-04 07:41 UTC
Sorry for this really dumb question, I am very new to Terraform and Flux, and trying to work it all out. 

I have created a Terraform file that uses the ESXI provider to create a VM.  Within that I use cloud-init to configure the VM and install k8s.  I would now like to install and configure flux onto this VM.  My question is, can I use this flux provider within the same tf file that created the VM, or do I install and run Terraform inside the VM?

**Comment by darkowlzz** [comment] 2022-04-04 10:50
Hi, it depends on your workflow. This terraform provider only requires kubeconfig of the target cluster to install flux if you only want to bootstrap flux using `flux_install` data source. If you also want to write the flux manifests in git, there are some extra requirements related to your git provider and repository access as shown in the bootstrap example https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/github .
You can use this within the same terraform configuration that creates the VM if you can fetch and provide the kubeconfig of the created cluster to the `flux_install` data source. Or you can have it independent, passing the kubeconfig separately, whatever works for your setup.

**Comment by swade1987** [comment] 2024-03-29 14:33
Hello @MarkLFT  ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Comment by MarkLFT** [comment] 2024-03-30 11:51
Thanks for reaching out. To answer your question, it no longer causes me any problems. Because now I only use Terraform to create the raw VM, then I have a some ansoble roles I created to fully commission the VM. Installing k8s, and installing flux cd to manage the k8s cluster.

**Comment by swade1987** [comment] 2024-03-30 15:53
@MarkLFT sounds good, could you possibly please close the issue. Thanks in advance.

**Closed** 2024-03-30 15:54 UTC
