### ISSUE TITLE
`flux_bootstrap_git` gets stuck forever if the deploy key lacks push access

### ISSUE THREAD

**Issue by leosunmo** [fluxcd/terraform-provider-flux#555] opened 2023-09-21 13:43 UTC
This issue was encountered using the Flux Terraform provider version 1.1.0, against a Gitlab repository.

The deploy key Flux was using to commit files when running `terraform apply` did not have permission to push to `master` as it was  a protected branch. This seems to have caused the Flux provider to just get stuck with no output (Terrafrom was just showing "modifying..." for 7+ minutes).

I had to manually kill the process, and when I retired it got stuck again, but as soon as I added push permissions for the Deploy Key Flux was using it succeeded, and Terraform moved on to the next resource.

**Comment by leosunmo** [comment] 2023-09-21 13:52
I seemingly had the same issue again, but this time it was actually stuck waiting for the main `flux-system` GitRepo to reconcile (I had to manually run `flux reconcile source git flux-system` or wait for the 10 minutes interval) and it "unblocked" it.

So perhaps the above issue is actually a red herring, and it was in fact waiting forever for the bootstrap Kustomization and Gitrepo to successfully reconcile, which it couldn't as the cluster was in a broken state.

**Comment by stefanprodan** [comment] 2023-09-21 14:32
By default all operations performed during bootstrap have a 5 minutes timeout. You can lower those if you want terrafrom to bailout faster, see https://registry.terraform.io/providers/fluxcd/flux/latest/docs/resources/bootstrap_git

**Comment by BurakCetin3129** [comment] 2024-03-13 14:36
Is there a way to disable flux push to git repo?

**Comment by swade1987** [comment] 2024-03-29 12:35
Hello @leosunmo ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Comment by swade1987** [comment] 2024-04-22 16:22
I am closing this issue due to over 3 weeks of inactivity. 
If you feel the issue should not have been closed, you can always open a new one.

**Closed by swade1987** 2024-04-22 16:22 UTC
Labels: request for feedback
