### ISSUE TITLE
Value Conversion Error - can't handle unknown value type

### ISSUE THREAD

**Issue by qlemaire-dvt** [fluxcd/terraform-provider-flux#558] opened 2023-09-29 20:37 UTC
Please note that i'm not very proficient in terraform so it might very well be an error from my part

provider version = ">= 1.1.1"

So i'm trying to make the installation of flux modulable in my terraform script, and I got this error : 

```
│ Error: Value Conversion Error
│
│   with provider["registry.terraform.io/fluxcd/flux"],
│   on provider.tf line 65, in provider "flux":
│   65: provider "flux" {
│
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│
│ Received unknown value, however the target type cannot handle unknown values. Use the corresponding `types` package type or a custom type that handles unknown values.
│
│ Path: git.ssh
│ Target Type: *provider.Ssh
│ Suggested Type: basetypes.ObjectValue
```

The lines throwing the error are the following : ( git.ssh )

```
provider "flux" {
  kubernetes = {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
    token                  = data.aws_eks_cluster_auth.this.token
  }
  git = {
    url = var.enable_gitops ? "ssh://git@gitlab.example.com/${module.gitops[0].gitops_repo_path}.git" : null
    ssh = var.enable_gitops ? {
      username    = "git"
      private_key = module.gitops[0].tls_private_key_pem
    } : null
  }
}
```

and this is how i call the module : 

```
module "gitops" {
  count       = var.enable_gitops ? 1 : 0
  source      = "./modules/gitops"
  environment = var.environment
}
```

Cheers

**Comment by shencan** [comment] 2023-10-14 14:31
same error with provider version = "1.1.2"  my provider config
```
provider "flux" {
  kubernetes = {
    config_path = "./${var.cluster_name}"
  }
  git = {
    url    = local.gitlab_url
    branch = var.gitlab_branch
    ssh = var.gitlab_prject_protocol == "ssh" ? {
      username    = "git"
      private_key = tls_private_key.flux.private_key_pem
    } : null
    http = var.gitlab_prject_protocol == "http" ? {
      username = var.gitlab_username
      password = var.gitlab_token
    } : null
  }
}
```

**Comment by swade1987** [comment] 2024-03-29 12:35
Hello @qlemaire-dvt / @shencan ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Comment by swade1987** [comment] 2024-04-24 17:07
Closing due to the lack of activity on the issue. If this issue is still important to you please feel free to raise another one.

**Closed by swade1987** 2024-04-24 17:07 UTC
Labels: request for feedback
