### ISSUE TITLE
GPG keys for flux with terraform. 

### ISSUE THREAD

**Issue by borjaOrtizLlamas** [fluxcd/terraform-provider-flux#245] opened 2022-02-02 08:16 UTC
HI, 
i want to set up flux v2 with terraform  but i don't find  the variable to add the gpg key and do the same like this option :"--gpg-key-ring=/root/gpg-signing-key/"

![image](https://user-images.githubusercontent.com/12540939/152116476-6e4419ae-9140-496f-99e0-90e75487931d.png)

i have ssh keys in this way and it's working: 

```

data "flux_sync" "main" {
  target_path = var.target_path
  url         = var.repo_url
  branch      = var.branch
}

resource "kubernetes_secret" "secret-ssh" {
  depends_on = [kubectl_manifest.install]

  metadata {
    name      = data.flux_sync.main.secret
    namespace = data.flux_sync.main.namespace
  }

  data = {
    identity        = base64decode(var.private_key)
    "identity.pub"  = base64decode(var.public_key)
    known_hosts     = local.known_hosts
  }
}


```
[I dont see it in the data sync anything  about it...](https://github.com/fluxcd/terraform-provider-flux/blob/main/docs/data-sources/sync.md)
Best regards

**Comment by borjaOrtizLlamas** [comment] 2022-02-02 08:24
Where is the document with all the attributes  of the terraform data "flux_sync"? I think with that i can complete it. 

Best regards

**Comment by exinos-git** [comment] 2022-08-10 18:59
It would be nice to have an option in the terraform to use the verify spec of the GitRepository.

**Comment by swade1987** [comment] 2024-03-29 14:43
Hello @yynmsl ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

----

Please see the following GPG key examples below:

1. https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/github-via-ssh-with-gpg
2. https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/gitlab-via-ssh-with-gpg

**Closed** 2024-04-01 13:16 UTC

**Comment by exinos-git** [comment] 2024-04-03 14:59
Hi @swade1987, I looked at your example I don't see anything to do with enabling GPG at all can you explain how this example uses GPG?

**Comment by swade1987** [comment] 2024-04-03 20:05
@exinos-git you can see the configuration in the provider.tf https://github.com/fluxcd/terraform-provider-flux/blob/main/examples/github-via-ssh-with-gpg/providers.tf
