### ISSUE TITLE
terraform how to enable aws-autologin-for-ecr

### ISSUE THREAD

**Issue by yynmsl** [fluxcd/terraform-provider-flux#256] opened 2022-02-18 11:00 UTC
Hi,

I use terraform to install flux 
```
data "flux_install" "main" {
  target_path    = var.target_path
  network_policy = false
  namespace   = var.flux_namespace
  components_extra = ["image-reflector-controller", "image-automation-controller"]
}
```
I use ImageRepository to pull my images from aws ecr, and I bind my aws pull ecr  roles to my k8s node to get images,
but  I get the error 
```
{"level":"info","ts":"2022-02-18T10:35:29.508Z","logger":"controller.imagerepository","msg":"No image credentials secret referenced, and ECR authentication is not enabled. To enable, set the controller flag --aws-autologin-for-ecr","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageRepository","name":"podinfo","namespace":"flux-system"}
```
I search document in terraform to enable  ` flag --aws-autologin-for-ecr` but not find, so could you give a demo, thanks!

**Comment by tibz-enex** [comment] 2022-06-01 13:27
Hi, 

Having same issue as yynmsl, would like to enable the flag

**Comment by tfrigini** [comment] 2022-06-09 01:45
Hi here I had created a patch in a variable defined in a local block, then I used this local variable as my kustomize file content, like this exemple:

`local {
  kustomize_patches = <<EOT
${data.flux_sync.main.kustomize_content}
patches:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: image-reflector-controller
    namespace: flux-system
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --aws-autologin-for-ecr
EOT
}

resource "github_repository_file" "kustomize" {
  count = var.deploy_flux ? 1 : 0

  repository          = data.github_repository.main.name
  file                = data.flux_sync.main.kustomize_path
  content             = local.kustomize_patches
  branch              = var.branch
}`

**Comment by Dgadavin** [comment] 2022-12-02 07:53
Hello. But this is only generate kustomization.yaml file but not apply it to Kubernetes. Maybe someone know how to do this with auto apply to K8S without doing manual action like `kubectl apply -k .` from flux directory. 
Thanks

**Comment by phillebaba** [comment] 2022-12-02 09:26
We are already using the kubectl provider to apply the other manifests.
https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs

**Comment by swade1987** [comment] 2024-03-29 14:41
Hello @yynmsl   ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

----

Please note that only the `flux_bootstrap_git` resource is being maintained within the provider for the foreseeable future.

**Comment by tfrigini** [comment] 2024-03-30 00:51
Hello, thanks for your answer. I have achived this using the config proposed in the fluxcd documentation which use a patch to set configs and iam roled

**Comment by swade1987** [comment] 2024-03-30 01:54
> Hello, thanks for your answer. I have achived this using the config proposed in the fluxcd documentation which use a patch to set configs and iam roles

@tfrigini using the flux_bootstrap_git resource? Please note all other data sources and resources are to be deprecated in the next release in April.

**Closed** 2024-04-01 13:16 UTC
