### ISSUE TITLE
flux_install should not have target_path as required

### ISSUE THREAD

**Issue by SebTardif** [fluxcd/terraform-provider-flux#414] opened 2023-03-11 12:00 UTC
There is this weird required valued for Terraform data "flux_install" called "target_path".  https://registry.terraform.io/providers/fluxcd/flux/latest/docs/data-sources/install#target_path

It's not used by all the use cases I imagine, and also not used by the official example here -> https://github.com/fluxcd/terraform-provider-flux/blob/main/examples/install/main.tf

We are required to set something, can be anything, and the outcome will be the exact same! 

Since my brain tried to make sense of it at the beginning, I interpreted that to be the path when the yaml will be persisted to, but it's not what this is doing. It just create a 'path' output value like -> "path" = "myTARGET_PATH/flux-system/gotk-components.yaml"

The main use case for this Terraform data.flux_install  is to get the yaml that install fluxcd, then extra Terraform code can apply it to the cluster. The yaml that tell fluxcd where to pull from git to do fluxcd upgrade is not part of this, so the 'path' above, is not used.

**Comment by phillebaba** [comment] 2023-03-15 10:28
I don't think that you are going to have an issue with the new `flux_bootstrap_git` resource. As we are trying to get people to move away from using the datasource method to bootstrap flux I would advise you to have a look at it instead.

https://registry.terraform.io/providers/fluxcd/flux/latest/docs/resources/bootstrap_git

**Comment by Just-Insane** [comment] 2023-03-22 15:59
The guide linked on that page doesn't seem to exist, and the bootstrap with GitHub guide which *sounds* like it's the same makes use of the data sources. Is that expected?

I suspect the correct guide for the new `flux_bootstrap_git` resource is: https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/bootstrap_github_ssh?

**Comment by phillebaba** [comment] 2023-03-23 11:38
Yes that is the guide, thanks for telling me about the broken link, will fix that.

**Comment by swade1987** [comment] 2024-03-29 14:33
Hello @SebTardif / @phillebaba  ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

**Comment by swade1987** [comment] 2024-04-01 13:28
Hi @SebTardif  👋

I hope you are doing well! As part of our ongoing effort to maintain and improve the quality of our project, I've been reviewing open issues and came across the one you've reported. First off, thank you for taking the time to contribute by reporting this issue; your input is crucial to us.

Upon reviewing the details of your issue, I noticed that it involves the use of a resource or feature that has yet to be supported since the 1.0.0 release of our project, which was approximately 9 months ago. This might be a key factor in the challenges you're experiencing. We understand that changes and deprecations can impact your work, and we're here to help navigate these transitions. If there are specific reasons you've continued using this unsupported resource or if there's any way we can assist in migrating to a supported alternative, please let us know.

Additionally, to ensure the efficient management of our issue tracker and to focus on issues that are actively affecting our community, we have implemented a policy for issues that remain inactive. If there is no activity on this issue within the next 3 weeks, we will consider the issue inactive and close it for you. This doesn't mean your issue is not important to us, but rather that we aim to keep our focus on actively pursued concerns. Of course, if the issue continues or if you have further updates in the future, feel free to reopen the issue or create a new one.

Thank you once again for your contribution to our project. Your feedback not only helps us improve but also supports the broader community in overcoming similar challenges. We look forward to hearing from you and hope to resolve any outstanding concerns together.

Best regards,

Steve

**Closed** 2024-04-01 14:22 UTC
